### ISSUE TITLE
. in database name

### ISSUE THREAD

**Issue by wkwkgit** [reliese/laravel#136]
At table with . in name it hangs:

#2 /web/project_path/application/vendor/reliese/laravel/src/Meta/MySql/Schema.php(80): Illuminate\\Database\\Connection->select('SHOW FULL TABLE...')
#3 /web/project_path/application/vendor/reliese/laravel/src/Meta/MySql/Schema.php(64): Reliese\\Meta\\MySql\\Schema->fetchTables('table.withdot...')

. is used to keep the domain name and database name the same. Also, it just cute.

**Comment by CristianLlanos** [comment]
This is a curious use case for a dot. Unfortunately, It is not supported.

**Comment by castrok** [comment]
How do i solve it. I need use the dot for patters reasons.

**Comment by CristianLlanos** [comment]
I encourage you to make a Pull Request with a fix. Thanks.

**Comment by castrok** [comment]
If i'm asking for a solution its becouse i dont know how to fix it !

**Comment by CristianLlanos** [comment]
If a fix is to be made, the code under `Reliese\Meta\MySql\Schema->fetchTables()` must be changed in order to support table names with dots. I'm sorry if this does not help.

**Comment by paulhennell** [comment]
This issue along with #170 caused problems for me - simply having a table with a dot in your db, even with no relation to the schema scanned completely  breaks the code.

I took a look at `fetchTables()`, but the issue is actually in `wrap()` where it intentionally splits on any '.' characters - I'm not sure how you'd avoid that in this case, while still keeping it for cases were it's needed. 

For me the easiest solution was simply to rename `table.suffix` tables to `table_suffix`, which wasn't too hard when I realised that's what the problem is. Absent a fix it might be worth adding something to the readme that this package will not work when your mysql contains *any* table with a dot in the name.

**Comment by CristianLlanos** [comment]
Thanks for sharing, @paulhennell. It'd be nice accepting a pull request updating the readme from you :)
