### ISSUE TITLE
Unknown column 'BASE TABLE' in 'where clause'

### ISSUE THREAD

**Issue by andrey-helldar** [reliese/laravel#39]
I'm using a connection to two databases in Laravel 5.5 project with MySQL 5.719:

**.env:**
```
DB_CONNECTION=mysql
DB_INFO_CONNECTION=information
```

In MySQL, there are several tables, the first of which is `discount`.

When I call the `php artisan code:models` command (and `php artisan code:models --connection=information`, and `php artisan code:models --connection=mysql`, and `php artisan code:models --table=users`), I get an error:

```
[Illuminate\Database\QueryException]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause' (SQL: SHOW FULL TABLES FROM `discount` WHERE Table_type="BASE TABLE")

[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause'

[PDOException]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause'
```

**Stack Trace:**
```
[2017-10-24 13:09:10] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause' (SQL: SHOW FULL TABLES FROM `discount` WHERE Table_type="BASE TABLE") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause' (SQL: SHOW FULL TABLES FROM `discount` WHERE Table_type=\"BASE TABLE\") at C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause' at C:\\OpenServer\\domains\\myproject.dev\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:79, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'BASE TABLE' in 'where clause' at C:\\OpenServer\\domains\\myproject.dev\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:77)
[stacktrace]
#0 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('SHOW FULL TABLE...', Array, Object(Closure))
#1 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(333): Illuminate\\Database\\Connection->run('SHOW FULL TABLE...', Array, Object(Closure))
#2 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\MySql\\Schema.php(80): Illuminate\\Database\\Connection->select('SHOW FULL TABLE...')
#3 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\MySql\\Schema.php(64): Reliese\\Meta\\MySql\\Schema->fetchTables('discount')
#4 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\MySql\\Schema.php(47): Reliese\\Meta\\MySql\\Schema->load()
#5 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php(86): Reliese\\Meta\\MySql\\Schema->__construct('discount', Object(Illuminate\\Database\\MySqlConnection))
#6 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php(74): Reliese\\Meta\\SchemaManager->makeMapper('discount')
#7 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php(59): Reliese\\Meta\\SchemaManager->make('discount')
#8 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php(44): Reliese\\Meta\\SchemaManager->boot()
#9 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(100): Reliese\\Meta\\SchemaManager->__construct(Object(Illuminate\\Database\\MySqlConnection))
#10 C:\\OpenServer\\domains\\myproject.dev\\vendor\
eliese\\laravel\\src\\Coders\\Console\\CodeModelsCommand.php(69): Reliese\\Coders\\Model\\Factory->on('information')
#11 [internal function]: Reliese\\Coders\\Console\\CodeModelsCommand->handle()
#12 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#13 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(180): Illuminate\\Container\\Container->call(Array)
#17 C:\\OpenServer\\domains\\myproject.dev\\vendor\\symfony\\console\\Command\\Command.php(262): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 C:\\OpenServer\\domains\\myproject.dev\\vendor\\symfony\\console\\Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\OpenServer\\domains\\myproject.dev\\vendor\\symfony\\console\\Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Reliese\\Coders\\Console\\CodeModelsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 C:\\OpenServer\\domains\\myproject.dev\\vendor\\symfony\\console\\Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 C:\\OpenServer\\domains\\myproject.dev\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\\OpenServer\\domains\\myproject.dev\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"} 
```

**Comment by CristianLlanos** [comment]
This is weird :thinking: Does your database user have the right permissions to use `show full tables...`?

**Comment by andrey-helldar** [comment]
Yes, there are full rights.
I develop on the local computer.

**Comment by CristianLlanos** [comment]
Do you mind running this query on your sql editor?
```sql
SHOW FULL TABLES FROM `discount` WHERE Table_type="BASE TABLE"
```
Does it show the same error?

**Comment by andrey-helldar** [comment]
Yes, the code is executed in the MySQL client.

And, with your help, found a problem:

Fulfilled the query `DB :: select ('SHOW FULL TABLES FROM discount WHERE Table_type="BASE TABLE"')` and received the same error. I started looking further and found the following: when developing, I use a grouping that, when `strict` mode is enabled, causes an error. To solve this error, a list of rules was registered in the `modes` parameter, except for `ONLY_FULL_GROUP_BY`.

So, the problem I described here occurred when the option `ANSI_QUOTES` was turned on. As soon as I turned it off, the problem disappeared.

Not correct `config/database.php`:
```
        'mysql' => [
            'driver'      => 'mysql',
            'host'        => env('DB_HOST', '127.0.0.1'),
            'port'        => env('DB_PORT', '3306'),
            'database'    => env('DB_DATABASE', 'forge'),
            'username'    => env('DB_USERNAME', 'forge'),
            'password'    => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_unicode_ci',
            'prefix'      => '',
            'strict'      => true,
            'engine'      => null,
            'modes'       => [
                'ALLOW_INVALID_DATES',
                'ANSI_QUOTES',
                'ERROR_FOR_DIVISION_BY_ZERO',
                'HIGH_NOT_PRECEDENCE',
                'IGNORE_SPACE',
                'NO_AUTO_CREATE_USER',
                'NO_AUTO_VALUE_ON_ZERO',
                'NO_BACKSLASH_ESCAPES',
                'NO_DIR_IN_CREATE',
                'NO_ENGINE_SUBSTITUTION',
                'NO_FIELD_OPTIONS',
                'NO_KEY_OPTIONS',
                'NO_TABLE_OPTIONS',
                'NO_UNSIGNED_SUBTRACTION',
                'NO_ZERO_DATE',
                'NO_ZERO_IN_DATE',
                //'ONLY_FULL_GROUP_BY',
                'PAD_CHAR_TO_FULL_LENGTH',
                'PIPES_AS_CONCAT',
                'REAL_AS_FLOAT',
                'STRICT_ALL_TABLES',
                'STRICT_TRANS_TABLES',
            ],
        ],
```

**Correct** `config/database.php`:
```
        'mysql' => [
            'driver'      => 'mysql',
            'host'        => env('DB_HOST', '127.0.0.1'),
            'port'        => env('DB_PORT', '3306'),
            'database'    => env('DB_DATABASE', 'forge'),
            'username'    => env('DB_USERNAME', 'forge'),
            'password'    => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset'     => 'utf8mb4',
            'collation'   => 'utf8mb4_unicode_ci',
            'prefix'      => '',
            'strict'      => true,
            'engine'      => null,
            'modes'       => [
                'ALLOW_INVALID_DATES',
                //'ANSI_QUOTES',
                'ERROR_FOR_DIVISION_BY_ZERO',
                'HIGH_NOT_PRECEDENCE',
                'IGNORE_SPACE',
                'NO_AUTO_CREATE_USER',
                'NO_AUTO_VALUE_ON_ZERO',
                'NO_BACKSLASH_ESCAPES',
                'NO_DIR_IN_CREATE',
                'NO_ENGINE_SUBSTITUTION',
                'NO_FIELD_OPTIONS',
                'NO_KEY_OPTIONS',
                'NO_TABLE_OPTIONS',
                'NO_UNSIGNED_SUBTRACTION',
                'NO_ZERO_DATE',
                'NO_ZERO_IN_DATE',
                //'ONLY_FULL_GROUP_BY',
                'PAD_CHAR_TO_FULL_LENGTH',
                'PIPES_AS_CONCAT',
                'REAL_AS_FLOAT',
                'STRICT_ALL_TABLES',
                'STRICT_TRANS_TABLES',
            ],
        ],
```

**Comment by CristianLlanos** [comment]
Thanks for your input Andrey. I'm glad you managed to make it work :+1:

**Comment by andrey-helldar** [comment]
Thank you for the package!

And why he thought about it - I made changes to the configuration and, at the same time, installed the package. 😃
