### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by andrey-helldar** [reliese/laravel#40]
I created a clean project on Laravel with the MySQL 5.7 database.
I connected only your package, and performed one by one:

```
php artisan migrate:install
php artisan code:models
```

I get an error:

```
[2017-10-24 10:44:34] local.ERROR: count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Model.php:684)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', 'C:\\\\OpenServer\\\\d...', 684, Array)
#1 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Model.php(684): count(NULL)
#2 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(309): Reliese\\Coders\\Model\\Model->hasCustomPrimaryKey()
#3 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(233): Reliese\\Coders\\Model\\Factory->body(Object(Reliese\\Coders\\Model\\Model))
#4 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(148): Reliese\\Coders\\Model\\Factory->fillTemplate('<?php\
\
/**\
 * C...', Object(Reliese\\Coders\\Model\\Model))
#5 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(118): Reliese\\Coders\\Model\\Factory->create('helpers', 'password_resets')
#6 C:\\OpenServer\\domains\\test123\\vendor\
eliese\\laravel\\src\\Coders\\Console\\CodeModelsCommand.php(69): Reliese\\Coders\\Model\\Factory->map('helpers')
#7 [internal function]: Reliese\\Coders\\Console\\CodeModelsCommand->handle()
#8 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#9 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(180): Illuminate\\Container\\Container->call(Array)
#13 C:\\OpenServer\\domains\\test123\\vendor\\symfony\\console\\Command\\Command.php(262): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 C:\\OpenServer\\domains\\test123\\vendor\\symfony\\console\\Application.php(888): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 C:\\OpenServer\\domains\\test123\\vendor\\symfony\\console\\Application.php(224): Symfony\\Component\\Console\\Application->doRunCommand(Object(Reliese\\Coders\\Console\\CodeModelsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 C:\\OpenServer\\domains\\test123\\vendor\\symfony\\console\\Application.php(125): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 C:\\OpenServer\\domains\\test123\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 C:\\OpenServer\\domains\\test123\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"} 
```
`helpers` - it's name of database.

**Comment by CristianLlanos** [comment]
I believe it's failing because the table doesn't have a primary key and my code doesn't handle well that situation :/ We need a quick fix in this line https://github.com/reliese/laravel/blob/master/src/Coders/Model/Model.php#L724 apparently. I'll try to have a look at it at the weekend. However, you can make a pull request if you'd like :) Thanks.

**Comment by CristianLlanos** [comment]
If you don't need a model for that table you can also ignore it from the code generation process https://github.com/reliese/laravel/blob/master/config/models.php#L265.
